name: Duster

on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]

jobs:
  duster:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Duster
        uses: tighten/duster-action@v3
        with:
          args: lint

  duster-fix:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref }}
          persist-credentials: true

      - name: Duster Fix
        uses: tighten/duster-action@v3
        with:
          args: fix

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Dusting
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
